-- =============================================================================
-- AFYA — Colonnes patient (fiche admin) + table constantes vitales
-- Idempotent (Oracle noms de tables en majuscules)
-- =============================================================================

-- patients : post-nom, employeur, matricule, profession, conjoint
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'PATIENTS' AND column_name = 'POST_NAME';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE patients ADD post_name VARCHAR2(120)';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'PATIENTS' AND column_name = 'EMPLOYER';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE patients ADD employer VARCHAR2(120)';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'PATIENTS' AND column_name = 'EMPLOYEE_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE patients ADD employee_id VARCHAR2(80)';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'PATIENTS' AND column_name = 'PROFESSION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE patients ADD profession VARCHAR2(120)';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'PATIENTS' AND column_name = 'SPOUSE_NAME';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE patients ADD spouse_name VARCHAR2(120)';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'PATIENTS' AND column_name = 'SPOUSE_PROFESSION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE patients ADD spouse_profession VARCHAR2(120)';
  END IF;
END;
/

-- Relevés de constantes liés à une admission
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'VITAL_SIGN_READINGS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE vital_sign_readings (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admission_id NUMBER NOT NULL,
        recorded_at TIMESTAMP NOT NULL,
        slot VARCHAR2(20),
        systolic_bp NUMBER(3),
        diastolic_bp NUMBER(3),
        pulse_bpm NUMBER(3),
        temperature_celsius NUMBER(5,2),
        weight_kg NUMBER(8,2),
        diuresis_ml NUMBER(10),
        stools_note VARCHAR2(500)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints WHERE constraint_name = 'FK_VSR_ADMISSION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE vital_sign_readings ADD CONSTRAINT fk_vsr_admission FOREIGN KEY (admission_id) REFERENCES admissions (id)]';
  END IF;
END;
/
