-- =============================================================================
-- AFYA — Prescriptions, administrations médicamenteuses, formulaire clinique admission
-- =============================================================================

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'PRESCRIPTION_LINES';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE prescription_lines (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admission_id NUMBER NOT NULL,
        medication_name VARCHAR2(500) NOT NULL,
        dosage_text VARCHAR2(500),
        frequency_text VARCHAR2(255),
        instructions_text CLOB,
        prescriber_name VARCHAR2(120),
        start_date DATE NOT NULL,
        end_date DATE,
        active NUMBER(1) DEFAULT 1 NOT NULL,
        created_at TIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints WHERE constraint_name = 'FK_PRESCRIPTION_ADMISSION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE prescription_lines ADD CONSTRAINT fk_prescription_admission FOREIGN KEY (admission_id) REFERENCES admissions (id)]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'MEDICATION_ADMINISTRATIONS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE medication_administrations (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        prescription_line_id NUMBER NOT NULL,
        administration_date DATE NOT NULL,
        slot VARCHAR2(20) NOT NULL,
        administered NUMBER(1) DEFAULT 0 NOT NULL,
        CONSTRAINT uk_med_admin_line_date_slot UNIQUE (prescription_line_id, administration_date, slot)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints WHERE constraint_name = 'FK_MEDADM_PRESCRIPTION_LINE';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE medication_administrations ADD CONSTRAINT fk_medadm_prescription_line FOREIGN KEY (prescription_line_id) REFERENCES prescription_lines (id)]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'ADMISSION_CLINICAL_FORMS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE admission_clinical_forms (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admission_id NUMBER NOT NULL,
        antecedents_text CLOB,
        anamnesis_text CLOB,
        physical_exam_pulmonary_text CLOB,
        physical_exam_cardiac_text CLOB,
        physical_exam_abdominal_text CLOB,
        physical_exam_neurological_text CLOB,
        physical_exam_misc_text CLOB,
        paraclinical_text CLOB,
        conclusion_text CLOB,
        CONSTRAINT uk_acf_admission UNIQUE (admission_id)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints WHERE constraint_name = 'FK_ACF_ADMISSION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE admission_clinical_forms ADD CONSTRAINT fk_acf_admission FOREIGN KEY (admission_id) REFERENCES admissions (id)]';
  END IF;
END;
/
