CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(64 CHAR) NOT NULL UNIQUE,
    label VARCHAR2(120 CHAR) NOT NULL
);

CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

INSERT INTO roles (code, label)
SELECT 'ROLE_ADMIN', 'Admin' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'ROLE_ADMIN');

INSERT INTO roles (code, label)
SELECT 'ROLE_MEDECIN', 'Médecin' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'ROLE_MEDECIN');

INSERT INTO roles (code, label)
SELECT 'ROLE_INFIRMIER', 'Infirmier(ère)' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'ROLE_INFIRMIER');

INSERT INTO roles (code, label)
SELECT 'ROLE_RECEPTION', 'Réceptionniste' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'ROLE_RECEPTION');

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM app_users u
JOIN roles r ON INSTR(',' || UPPER(NVL(u.roles, '')) || ',', ',' || r.code || ',') > 0
WHERE NOT EXISTS (
    SELECT 1
    FROM user_roles ur
    WHERE ur.user_id = u.id AND ur.role_id = r.id
);
