CREATE TABLE hospital_services (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(120 CHAR) NOT NULL UNIQUE,
    active NUMBER(1) DEFAULT 1 NOT NULL
);

INSERT INTO hospital_services (name, active)
SELECT 'Urgences', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM hospital_services WHERE UPPER(name) = UPPER('Urgences'));

INSERT INTO hospital_services (name, active)
SELECT 'Médecine interne', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM hospital_services WHERE UPPER(name) = UPPER('Médecine interne'));

INSERT INTO hospital_services (name, active)
SELECT 'Chirurgie', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM hospital_services WHERE UPPER(name) = UPPER('Chirurgie'));

INSERT INTO hospital_services (name, active)
SELECT 'Pédiatrie', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM hospital_services WHERE UPPER(name) = UPPER('Pédiatrie'));

INSERT INTO hospital_services (name, active)
SELECT 'Maternité', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM hospital_services WHERE UPPER(name) = UPPER('Maternité'));
