CREATE TABLE patient_dossier_sequences (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_year NUMBER(4) NOT NULL,
    letter_block VARCHAR2(4 CHAR) NOT NULL,
    sequence_number NUMBER(4) NOT NULL
);

ALTER TABLE patient_dossier_sequences
    ADD CONSTRAINT uk_patient_dossier_sequences_year UNIQUE (sequence_year);
